import Head from "next/head";
import styles from "../styles/Home.module.css";
// import styles2 from "../styles/Home2.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
       <style jsx >
          {`
            .mySpan {
              color: red;
              text-shadow: 1px 1px 3px blue;
            }
          `}
        </style>
      <Head>
        <title>Hunting Coder || Ariful Islam</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="next, hunting coder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
        {/* <script src='/sc.js' ></script> */}
       
      </Head>
      {/* <Script src="/sc.js" strategy='lazyOnload'></Script> */}
     

      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className={"mySpan"}>Hunting Code</span>
        </h1>
        <img className={styles.myImg} src={'/coder.jpg'} width={237} height={157}
              alt="Coder Image"/>

        <p className={styles.description}>
          A blog for hunting coder by a hunting coder
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={"blogs"}>
          <h2>Latest Blog</h2>
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is the language used to design for web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is the language used to design for web</p>
          </div>
          <div className="blogItem">
            <h3>How to learn javascript in 2022?</h3>
            <p>Javascript is the language used to design for web</p>
          </div>
        </div>
      </main>

     
    </div>
  );
}
